language: node_js
dist: trusty
sudo: required
node_js:
  - "stable"
before_install:
  - stty cols 80
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox
cache:
  directories:
    - node_modules
before_script:
  - sudo apt install xsel
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - yarn global add serve
script: npm run build && npm test
